<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\RefCountry;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            ['name' => 'India',                'iso_code' => 'in', 'currency_symbol' => '₹',  'currency_code' => 'INR', 'currency_name' => 'Indian Rupee'],
            ['name' => 'United States',        'iso_code' => 'us', 'currency_symbol' => '$',  'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'United Kingdom',       'iso_code' => 'gb', 'currency_symbol' => '£',  'currency_code' => 'GBP', 'currency_name' => 'British Pound'],
            ['name' => 'United Arab Emirates', 'iso_code' => 'ae', 'currency_symbol' => null, 'currency_code' => 'AED', 'currency_name' => 'UAE Dirham'],
            ['name' => 'Australia',            'iso_code' => 'au', 'currency_symbol' => '$',  'currency_code' => 'AUD', 'currency_name' => 'Australian Dollar'],
            ['name' => 'Canada',               'iso_code' => 'ca', 'currency_symbol' => '$',  'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar'],
            ['name' => 'Singapore',            'iso_code' => 'sg', 'currency_symbol' => '$',  'currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar'],
            ['name' => 'Japan',                'iso_code' => 'jp', 'currency_symbol' => '¥',  'currency_code' => 'JPY', 'currency_name' => 'Japanese Yen'],
            ['name' => 'China',                'iso_code' => 'cn', 'currency_symbol' => '¥',  'currency_code' => 'CNY', 'currency_name' => 'Chinese Yuan'],
            ['name' => 'Thailand',             'iso_code' => 'th', 'currency_symbol' => '฿',  'currency_code' => 'THB', 'currency_name' => 'Thai Baht'],
            ['name' => 'Indonesia',            'iso_code' => 'id', 'currency_symbol' => 'Rp', 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah'],
            ['name' => 'Malaysia',             'iso_code' => 'my', 'currency_symbol' => 'RM', 'currency_code' => 'MYR', 'currency_name' => 'Malaysian Ringgit'],
            ['name' => 'South Africa',         'iso_code' => 'za', 'currency_symbol' => 'R',  'currency_code' => 'ZAR', 'currency_name' => 'South African Rand'],
            ['name' => 'Saudi Arabia',         'iso_code' => 'sa', 'currency_symbol' => null, 'currency_code' => 'SAR', 'currency_name' => 'Saudi Riyal'],
            ['name' => 'Qatar',                'iso_code' => 'qa', 'currency_symbol' => null, 'currency_code' => 'QAR', 'currency_name' => 'Qatari Riyal'],
            ['name' => 'New Zealand',          'iso_code' => 'nz', 'currency_symbol' => '$',  'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar'],
            ['name' => 'Germany',              'iso_code' => 'de', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'France',               'iso_code' => 'fr', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Italy',                'iso_code' => 'it', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Spain',                'iso_code' => 'es', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Netherlands',          'iso_code' => 'nl', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Switzerland',          'iso_code' => 'ch', 'currency_symbol' => 'Fr', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc'],
            ['name' => 'Sweden',               'iso_code' => 'se', 'currency_symbol' => 'kr', 'currency_code' => 'SEK', 'currency_name' => 'Swedish Krona'],
            ['name' => 'Norway',               'iso_code' => 'no', 'currency_symbol' => 'kr', 'currency_code' => 'NOK', 'currency_name' => 'Norwegian Krone'],
            ['name' => 'Denmark',              'iso_code' => 'dk', 'currency_symbol' => 'kr', 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone'],
            ['name' => 'Brazil',               'iso_code' => 'br', 'currency_symbol' => 'R$', 'currency_code' => 'BRL', 'currency_name' => 'Brazilian Real'],
            ['name' => 'Mexico',               'iso_code' => 'mx', 'currency_symbol' => '$',  'currency_code' => 'MXN', 'currency_name' => 'Mexican Peso'],
            ['name' => 'Argentina',            'iso_code' => 'ar', 'currency_symbol' => '$',  'currency_code' => 'ARS', 'currency_name' => 'Argentine Peso'],
            ['name' => 'Chile',                'iso_code' => 'cl', 'currency_symbol' => '$',  'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso'],
            ['name' => 'Colombia',             'iso_code' => 'co', 'currency_symbol' => '$',  'currency_code' => 'COP', 'currency_name' => 'Colombian Peso'],
            ['name' => 'Russia',               'iso_code' => 'ru', 'currency_symbol' => '₽',  'currency_code' => 'RUB', 'currency_name' => 'Russian Ruble'],
            ['name' => 'Turkey',               'iso_code' => 'tr', 'currency_symbol' => '₺',  'currency_code' => 'TRY', 'currency_name' => 'Turkish Lira'],
            ['name' => 'Poland',               'iso_code' => 'pl', 'currency_symbol' => 'zł', 'currency_code' => 'PLN', 'currency_name' => 'Polish Zloty'],
            ['name' => 'Egypt',                'iso_code' => 'eg', 'currency_symbol' => '£',  'currency_code' => 'EGP', 'currency_name' => 'Egyptian Pound'],
            ['name' => 'Nigeria',              'iso_code' => 'ng', 'currency_symbol' => '₦',  'currency_code' => 'NGN', 'currency_name' => 'Nigerian Naira'],
            ['name' => 'Kenya',                'iso_code' => 'ke', 'currency_symbol' => 'KSh', 'currency_code' => 'KES', 'currency_name' => 'Kenyan Shilling'],
            ['name' => 'Ghana',                'iso_code' => 'gh', 'currency_symbol' => '₵',  'currency_code' => 'GHS', 'currency_name' => 'Ghanaian Cedi'],
            ['name' => 'Morocco',              'iso_code' => 'ma', 'currency_symbol' => null, 'currency_code' => 'MAD', 'currency_name' => 'Moroccan Dirham'],
            ['name' => 'Ethiopia',             'iso_code' => 'et', 'currency_symbol' => 'Br', 'currency_code' => 'ETB', 'currency_name' => 'Ethiopian Birr'],
            ['name' => 'Tanzania',             'iso_code' => 'tz', 'currency_symbol' => 'Sh', 'currency_code' => 'TZS', 'currency_name' => 'Tanzanian Shilling'],
            ['name' => 'Pakistan',             'iso_code' => 'pk', 'currency_symbol' => '₨',  'currency_code' => 'PKR', 'currency_name' => 'Pakistani Rupee'],
            ['name' => 'Bangladesh',           'iso_code' => 'bd', 'currency_symbol' => '৳',  'currency_code' => 'BDT', 'currency_name' => 'Bangladeshi Taka'],
            ['name' => 'Sri Lanka',            'iso_code' => 'lk', 'currency_symbol' => '₨',  'currency_code' => 'LKR', 'currency_name' => 'Sri Lankan Rupee'],
            ['name' => 'Nepal',                'iso_code' => 'np', 'currency_symbol' => '₨',  'currency_code' => 'NPR', 'currency_name' => 'Nepalese Rupee'],
            ['name' => 'Myanmar',              'iso_code' => 'mm', 'currency_symbol' => 'K',  'currency_code' => 'MMK', 'currency_name' => 'Myanmar Kyat'],
            ['name' => 'Vietnam',              'iso_code' => 'vn', 'currency_symbol' => '₫',  'currency_code' => 'VND', 'currency_name' => 'Vietnamese Dong'],
            ['name' => 'Philippines',          'iso_code' => 'ph', 'currency_symbol' => '₱',  'currency_code' => 'PHP', 'currency_name' => 'Philippine Peso'],
            ['name' => 'South Korea',          'iso_code' => 'kr', 'currency_symbol' => '₩',  'currency_code' => 'KRW', 'currency_name' => 'South Korean Won'],
            ['name' => 'Hong Kong',            'iso_code' => 'hk', 'currency_symbol' => '$',  'currency_code' => 'HKD', 'currency_name' => 'Hong Kong Dollar'],
            ['name' => 'Taiwan',               'iso_code' => 'tw', 'currency_symbol' => '$',  'currency_code' => 'TWD', 'currency_name' => 'New Taiwan Dollar'],
            ['name' => 'Macau',                'iso_code' => 'mo', 'currency_symbol' => 'P',  'currency_code' => 'MOP', 'currency_name' => 'Macanese Pataca'],
            ['name' => 'Cambodia',             'iso_code' => 'kh', 'currency_symbol' => '៛',  'currency_code' => 'KHR', 'currency_name' => 'Cambodian Riel'],
            ['name' => 'Laos',                 'iso_code' => 'la', 'currency_symbol' => '₭',  'currency_code' => 'LAK', 'currency_name' => 'Lao Kip'],
            ['name' => 'Brunei',               'iso_code' => 'bn', 'currency_symbol' => '$',  'currency_code' => 'BND', 'currency_name' => 'Brunei Dollar'],
            ['name' => 'Mongolia',             'iso_code' => 'mn', 'currency_symbol' => '₮',  'currency_code' => 'MNT', 'currency_name' => 'Mongolian Tögrög'],
            ['name' => 'Kazakhstan',           'iso_code' => 'kz', 'currency_symbol' => '₸',  'currency_code' => 'KZT', 'currency_name' => 'Kazakhstani Tenge'],
            ['name' => 'Uzbekistan',           'iso_code' => 'uz', 'currency_symbol' => 'soʻm', 'currency_code' => 'UZS', 'currency_name' => 'Uzbekistani Som'],
            ['name' => 'Kuwait',               'iso_code' => 'kw', 'currency_symbol' => null, 'currency_code' => 'KWD', 'currency_name' => 'Kuwaiti Dinar'],
            ['name' => 'Bahrain',              'iso_code' => 'bh', 'currency_symbol' => null, 'currency_code' => 'BHD', 'currency_name' => 'Bahraini Dinar'],
            ['name' => 'Oman',                 'iso_code' => 'om', 'currency_symbol' => null, 'currency_code' => 'OMR', 'currency_name' => 'Omani Rial'],
            ['name' => 'Jordan',               'iso_code' => 'jo', 'currency_symbol' => null, 'currency_code' => 'JOD', 'currency_name' => 'Jordanian Dinar'],
            ['name' => 'Lebanon',              'iso_code' => 'lb', 'currency_symbol' => '£',  'currency_code' => 'LBP', 'currency_name' => 'Lebanese Pound'],
            ['name' => 'Israel',               'iso_code' => 'il', 'currency_symbol' => '₪',  'currency_code' => 'ILS', 'currency_name' => 'Israeli Shekel'],
            ['name' => 'Iran',                 'iso_code' => 'ir', 'currency_symbol' => '﷼',  'currency_code' => 'IRR', 'currency_name' => 'Iranian Rial'],
            ['name' => 'Iraq',                 'iso_code' => 'iq', 'currency_symbol' => 'ع.د', 'currency_code' => 'IQD', 'currency_name' => 'Iraqi Dinar'],
            ['name' => 'Afghanistan',          'iso_code' => 'af', 'currency_symbol' => '؋',  'currency_code' => 'AFN', 'currency_name' => 'Afghan Afghani'],
            ['name' => 'Azerbaijan',           'iso_code' => 'az', 'currency_symbol' => '₼',  'currency_code' => 'AZN', 'currency_name' => 'Azerbaijani Manat'],
            ['name' => 'Georgia',              'iso_code' => 'ge', 'currency_symbol' => '₾',  'currency_code' => 'GEL', 'currency_name' => 'Georgian Lari'],
            ['name' => 'Armenia',              'iso_code' => 'am', 'currency_symbol' => '֏',  'currency_code' => 'AMD', 'currency_name' => 'Armenian Dram'],
            ['name' => 'Portugal',             'iso_code' => 'pt', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Belgium',              'iso_code' => 'be', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Austria',              'iso_code' => 'at', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Greece',               'iso_code' => 'gr', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Czech Republic',       'iso_code' => 'cz', 'currency_symbol' => 'Kč', 'currency_code' => 'CZK', 'currency_name' => 'Czech Koruna'],
            ['name' => 'Hungary',              'iso_code' => 'hu', 'currency_symbol' => 'Ft', 'currency_code' => 'HUF', 'currency_name' => 'Hungarian Forint'],
            ['name' => 'Romania',              'iso_code' => 'ro', 'currency_symbol' => 'lei', 'currency_code' => 'RON', 'currency_name' => 'Romanian Leu'],
            ['name' => 'Ukraine',              'iso_code' => 'ua', 'currency_symbol' => '₴',  'currency_code' => 'UAH', 'currency_name' => 'Ukrainian Hryvnia'],
            ['name' => 'Finland',              'iso_code' => 'fi', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Ireland',              'iso_code' => 'ie', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Luxembourg',           'iso_code' => 'lu', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Iceland',              'iso_code' => 'is', 'currency_symbol' => 'kr', 'currency_code' => 'ISK', 'currency_name' => 'Icelandic Króna'],
            ['name' => 'Peru',                 'iso_code' => 'pe', 'currency_symbol' => 'S/', 'currency_code' => 'PEN', 'currency_name' => 'Peruvian Sol'],
            ['name' => 'Venezuela',            'iso_code' => 've', 'currency_symbol' => 'Bs.', 'currency_code' => 'VES', 'currency_name' => 'Venezuelan Bolívar'],
            ['name' => 'Ecuador',              'iso_code' => 'ec', 'currency_symbol' => '$',  'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Bolivia',              'iso_code' => 'bo', 'currency_symbol' => 'Bs', 'currency_code' => 'BOB', 'currency_name' => 'Bolivian Boliviano'],
            ['name' => 'Paraguay',             'iso_code' => 'py', 'currency_symbol' => '₲',  'currency_code' => 'PYG', 'currency_name' => 'Paraguayan Guaraní'],
            ['name' => 'Uruguay',              'iso_code' => 'uy', 'currency_symbol' => '$',  'currency_code' => 'UYU', 'currency_name' => 'Uruguayan Peso'],
            ['name' => 'Cuba',                 'iso_code' => 'cu', 'currency_symbol' => '$',  'currency_code' => 'CUP', 'currency_name' => 'Cuban Peso'],
            ['name' => 'Dominican Republic',   'iso_code' => 'do', 'currency_symbol' => '$',  'currency_code' => 'DOP', 'currency_name' => 'Dominican Peso'],
            ['name' => 'Guatemala',            'iso_code' => 'gt', 'currency_symbol' => 'Q',  'currency_code' => 'GTQ', 'currency_name' => 'Guatemalan Quetzal'],
            ['name' => 'Costa Rica',           'iso_code' => 'cr', 'currency_symbol' => '₡',  'currency_code' => 'CRC', 'currency_name' => 'Costa Rican Colón'],
            ['name' => 'Panama',               'iso_code' => 'pa', 'currency_symbol' => 'B/', 'currency_code' => 'PAB', 'currency_name' => 'Panamanian Balboa'],
            ['name' => 'Jamaica',              'iso_code' => 'jm', 'currency_symbol' => '$',  'currency_code' => 'JMD', 'currency_name' => 'Jamaican Dollar'],
            ['name' => 'Trinidad and Tobago',  'iso_code' => 'tt', 'currency_symbol' => '$',  'currency_code' => 'TTD', 'currency_name' => 'Trinidad and Tobago Dollar'],
            ['name' => 'Algeria',              'iso_code' => 'dz', 'currency_symbol' => 'دج', 'currency_code' => 'DZD', 'currency_name' => 'Algerian Dinar'],
            ['name' => 'Tunisia',              'iso_code' => 'tn', 'currency_symbol' => null, 'currency_code' => 'TND', 'currency_name' => 'Tunisian Dinar'],
            ['name' => 'Libya',                'iso_code' => 'ly', 'currency_symbol' => 'ل.د', 'currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar'],
            ['name' => 'Sudan',                'iso_code' => 'sd', 'currency_symbol' => '£',  'currency_code' => 'SDG', 'currency_name' => 'Sudanese Pound'],
            ['name' => 'Angola',               'iso_code' => 'ao', 'currency_symbol' => 'Kz', 'currency_code' => 'AOA', 'currency_name' => 'Angolan Kwanza'],
            ['name' => 'Mozambique',           'iso_code' => 'mz', 'currency_symbol' => 'MT', 'currency_code' => 'MZN', 'currency_name' => 'Mozambican Metical'],
            ['name' => 'Zambia',               'iso_code' => 'zm', 'currency_symbol' => 'ZK', 'currency_code' => 'ZMW', 'currency_name' => 'Zambian Kwacha'],
            ['name' => 'Zimbabwe',             'iso_code' => 'zw', 'currency_symbol' => '$',  'currency_code' => 'ZWL', 'currency_name' => 'Zimbabwean Dollar'],
            ['name' => 'Uganda',               'iso_code' => 'ug', 'currency_symbol' => 'Sh', 'currency_code' => 'UGX', 'currency_name' => 'Ugandan Shilling'],
            ['name' => 'Rwanda',               'iso_code' => 'rw', 'currency_symbol' => 'Fr', 'currency_code' => 'RWF', 'currency_name' => 'Rwandan Franc'],
            ['name' => 'Cameroon',             'iso_code' => 'cm', 'currency_symbol' => 'Fr', 'currency_code' => 'XAF', 'currency_name' => 'Central African CFA Franc'],
            ['name' => 'Senegal',              'iso_code' => 'sn', 'currency_symbol' => 'Fr', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => "Côte d'Ivoire",        'iso_code' => 'ci', 'currency_symbol' => 'Fr', 'currency_code' => 'XOF', 'currency_name' => 'West African CFA Franc'],
            ['name' => 'Madagascar',           'iso_code' => 'mg', 'currency_symbol' => 'Ar', 'currency_code' => 'MGA', 'currency_name' => 'Malagasy Ariary'],
            ['name' => 'Mauritius',            'iso_code' => 'mu', 'currency_symbol' => '₨',  'currency_code' => 'MUR', 'currency_name' => 'Mauritian Rupee'],
            ['name' => 'Maldives',             'iso_code' => 'mv', 'currency_symbol' => 'Rf', 'currency_code' => 'MVR', 'currency_name' => 'Maldivian Rufiyaa'],
            ['name' => 'Seychelles',           'iso_code' => 'sc', 'currency_symbol' => '₨',  'currency_code' => 'SCR', 'currency_name' => 'Seychellois Rupee'],
            ['name' => 'Papua New Guinea',     'iso_code' => 'pg', 'currency_symbol' => 'K',  'currency_code' => 'PGK', 'currency_name' => 'Papua New Guinean Kina'],
            ['name' => 'Fiji',                 'iso_code' => 'fj', 'currency_symbol' => '$',  'currency_code' => 'FJD', 'currency_name' => 'Fijian Dollar'],
            ['name' => 'Vanuatu',              'iso_code' => 'vu', 'currency_symbol' => 'Vt', 'currency_code' => 'VUV', 'currency_name' => 'Vanuatu Vatu'],
            ['name' => 'Samoa',                'iso_code' => 'ws', 'currency_symbol' => 'T',  'currency_code' => 'WST', 'currency_name' => 'Samoan Tālā'],
            ['name' => 'Tonga',                'iso_code' => 'to', 'currency_symbol' => 'T$', 'currency_code' => 'TOP', 'currency_name' => "Tongan Pa'anga"],
            ['name' => 'Timor-Leste',          'iso_code' => 'tl', 'currency_symbol' => '$',  'currency_code' => 'USD', 'currency_name' => 'US Dollar'],
            ['name' => 'Bulgaria',             'iso_code' => 'bg', 'currency_symbol' => 'лв', 'currency_code' => 'BGN', 'currency_name' => 'Bulgarian Lev'],
            ['name' => 'Croatia',              'iso_code' => 'hr', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Serbia',               'iso_code' => 'rs', 'currency_symbol' => 'din', 'currency_code' => 'RSD', 'currency_name' => 'Serbian Dinar'],
            ['name' => 'Slovakia',             'iso_code' => 'sk', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Slovenia',             'iso_code' => 'si', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Lithuania',            'iso_code' => 'lt', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Latvia',               'iso_code' => 'lv', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Estonia',              'iso_code' => 'ee', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Belarus',              'iso_code' => 'by', 'currency_symbol' => 'Br', 'currency_code' => 'BYN', 'currency_name' => 'Belarusian Ruble'],
            ['name' => 'Moldova',              'iso_code' => 'md', 'currency_symbol' => 'L',  'currency_code' => 'MDL', 'currency_name' => 'Moldovan Leu'],
            ['name' => 'Albania',              'iso_code' => 'al', 'currency_symbol' => 'L',  'currency_code' => 'ALL', 'currency_name' => 'Albanian Lek'],
            ['name' => 'North Macedonia',      'iso_code' => 'mk', 'currency_symbol' => 'ден', 'currency_code' => 'MKD', 'currency_name' => 'Macedonian Denar'],
            ['name' => 'Bosnia and Herzegovina', 'iso_code' => 'ba', 'currency_symbol' => 'KM', 'currency_code' => 'BAM', 'currency_name' => 'Bosnia and Herzegovina Convertible Mark'],
            ['name' => 'Montenegro',           'iso_code' => 'me', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Kosovo',               'iso_code' => 'xk', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Cyprus',               'iso_code' => 'cy', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Malta',                'iso_code' => 'mt', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Liechtenstein',        'iso_code' => 'li', 'currency_symbol' => 'Fr', 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc'],
            ['name' => 'Monaco',               'iso_code' => 'mc', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Andorra',              'iso_code' => 'ad', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'San Marino',           'iso_code' => 'sm', 'currency_symbol' => '€',  'currency_code' => 'EUR', 'currency_name' => 'Euro'],
            ['name' => 'Kyrgyzstan',           'iso_code' => 'kg', 'currency_symbol' => 'с',  'currency_code' => 'KGS', 'currency_name' => 'Kyrgyzstani Som'],
            ['name' => 'Tajikistan',           'iso_code' => 'tj', 'currency_symbol' => 'SM', 'currency_code' => 'TJS', 'currency_name' => 'Tajikistani Somoni'],
            ['name' => 'Turkmenistan',         'iso_code' => 'tm', 'currency_symbol' => 'T',  'currency_code' => 'TMT', 'currency_name' => 'Turkmenistani Manat'],
            ['name' => 'Syria',                'iso_code' => 'sy', 'currency_symbol' => '£',  'currency_code' => 'SYP', 'currency_name' => 'Syrian Pound'],
            ['name' => 'Yemen',                'iso_code' => 'ye', 'currency_symbol' => '﷼',  'currency_code' => 'YER', 'currency_name' => 'Yemeni Rial'],
            ['name' => 'Libya',                'iso_code' => 'ly', 'currency_symbol' => 'ل.د', 'currency_code' => 'LYD', 'currency_name' => 'Libyan Dinar'],
            ['name' => 'Bhutan',               'iso_code' => 'bt', 'currency_symbol' => 'Nu', 'currency_code' => 'BTN', 'currency_name' => 'Bhutanese Ngultrum'],
        ];

        // Remove duplicates by iso_code before inserting
        $unique = collect($countries)->unique('iso_code')->values()->toArray();

        // Build a lookup map: uppercase ISO2 → ref_countries.id
        $refCountryMap = RefCountry::query()
            ->whereNotNull('iso2')
            ->pluck('id', 'iso2')
            ->mapWithKeys(fn ($id, $iso2) => [strtolower($iso2) => $id])
            ->toArray();

        foreach ($unique as $country) {
            $country['ref_country_id'] = $refCountryMap[$country['iso_code']] ?? null;

            Country::query()->updateOrCreate(
                ['iso_code' => $country['iso_code']],
                $country
            );
        }
    }
}
