<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('manual_refund_requests', function (Blueprint $table) {
            $table->id();
            $table->foreignId('user_id')->constrained()->onDelete('cascade');
            $table->foreignId('booking_id')->unique()->constrained()->onDelete('cascade');
            $table->string('ref_id', 100)->nullable()->comment('Transaction reference from customer, e.g. TXN102451');
            $table->string('account_holder_name');
            $table->string('bank_name');
            $table->string('account_number');
            $table->string('ifsc_swift_code');
            $table->decimal('amount', 10, 2);
            $table->text('message')->nullable();
            $table->enum('status', ['pending_review', 'transferred'])->default('pending_review');
            $table->string('transaction_image')->nullable()->comment('Proof of bank transfer uploaded by admin');
            $table->string('transfer_reference_id')->nullable()->comment('Auto-generated by admin on transfer, e.g. TRF7845123');
            $table->timestamp('transferred_at')->nullable();
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('manual_refund_requests');
    }
};
