<?php

namespace App\Filament\Resources\Blogs\Schemas;

use App\Enums\BlogCategoryStatus;
use App\Models\Blog;
use App\Models\BlogCategory;
use Filament\Actions\Action;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Components\View;
use Filament\Schemas\Schema;
use Illuminate\Support\Str;

class BlogForm
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->columns(3)
            ->components([
                Section::make(__('admin.blog_configuration'))
                    ->columnSpan(2)
                    ->schema([
                        TextInput::make('title')
                            ->label(__('admin.blog_title'))
                            ->placeholder(__('admin.eg_search_your_stay'))
                            ->required()
                            ->maxLength(255)
                            ->live(onBlur: true)
                            ->afterStateUpdated(function (?string $state, callable $set, ?string $operation, $record): void {
                                $slug = Str::slug($state ?? '');
                                $original = $slug;
                                $counter = 2;
                                $ignoreId = $operation === 'edit' && $record ? $record->id : null;

                                while (Blog::query()->where('slug', $slug)->when($ignoreId, fn ($q) => $q->where('id', '!=', $ignoreId))->exists()) {
                                    $slug = $original.'-'.$counter;
                                    $counter++;
                                }

                                $set('slug', $slug);
                            }),
                        TextInput::make('slug')
                            ->label(__('admin.slug_url_friendly'))
                            ->placeholder(__('admin.blogs'))
                            ->required()
                            ->maxLength(255)
                            ->unique(table: Blog::class, column: 'slug', ignoreRecord: true)
                            ->validationMessages(['unique' => 'This slug is already taken.'])
                            ->helperText(__('admin.the_slug_will_be_autogenerated_from_the_blog_title_and_can_be_edited_if_needed')),
                        Select::make('blog_category_id')
                            ->label(__('admin.category'))
                            ->placeholder(__('admin.select_a_category'))
                            ->options(fn ($record) => BlogCategory::query()
                                ->where(function ($q) use ($record): void {
                                    $q->where('status', BlogCategoryStatus::Published->value);
                                    if ($record?->blog_category_id) {
                                        $q->orWhere('id', $record->blog_category_id);
                                    }
                                })
                                ->pluck('name', 'id'))
                            ->required()
                            ->searchable()
                            ->live(onBlur: true)
                            ->suffixAction(
                                Action::make('manageCategories')
                                    ->label(__('admin.manage_categories'))
                                    ->link()
                                    ->url(fn () => route('filament.admin.resources.blogs.index', ['tab' => 'categories']))
                                    ->openUrlInNewTab(),
                            ),
                        Textarea::make('short_description')
                            ->label(__('admin.short_description'))
                            ->placeholder(__('admin.brief_description_of_the_blog'))
                            ->required()
                            ->rows(3)
                            ->maxLength(500)
                            ->live(onBlur: true),
                        RichEditor::make('content')
                            ->label(__('admin.main_content'))
                            ->placeholder(__('admin.add_blog_details_page'))
                            ->required()
                            ->toolbarButtons([
                                ['bold', 'italic', 'underline', 'strike', 'link', 'textColor', 'highlight'],
                                ['h1', 'h2', 'h3', 'lead', 'small'],
                                ['alignStart', 'alignCenter', 'alignEnd', 'alignJustify'],
                                ['blockquote', 'codeBlock', 'bulletList', 'orderedList', 'horizontalRule'],
                                ['table', 'grid', 'details', 'attachFiles'],
                                ['undo', 'redo', 'clearFormatting'],
                            ])
                            ->floatingToolbars([
                                'table' => [
                                    'tableAddColumnBefore', 'tableAddColumnAfter', 'tableDeleteColumn',
                                    'tableAddRowBefore', 'tableAddRowAfter', 'tableDeleteRow',
                                    'tableMergeCells', 'tableSplitCell',
                                    'tableToggleHeaderRow', 'tableDelete',
                                ],
                            ])
                            ->fileAttachmentsDirectory('blogs/content')
                            ->fileAttachmentsDisk('public')
                            ->fileAttachmentsMaxSize(2048),
                        FileUpload::make('cover_image')
                            ->label(__('admin.blog_cover_image'))
                            ->image()
                            ->disk('public')
                            ->directory('blogs/covers')
                            ->visibility('public')
                            ->maxSize(2048)
                            ->acceptedFileTypes(['image/jpeg', 'image/png'])
                            ->helperText(__('admin.maximum_size_2mb_resolution_1620823_px_supported_files_jpgpng'))
                            ->required()
                            ->live(),
                        TextInput::make('read_time_minutes')
                            ->label(__('admin.read_time_minutes'))
                            ->placeholder(__('admin.eg_5'))
                            ->numeric()
                            ->minValue(1)
                            ->maxValue(120)
                            ->required()
                            ->helperText(__('admin.estimated_time_to_read_the_blog_in_minutes')),
                    ]),
                View::make('filament.schemas.components.blog-preview')
                    ->columnSpan(1)
                    ->extraAttributes(['class' => 'fi-blog-preview-sticky']),
                Section::make(__('admin.seo_configuration'))
                    ->columnSpan(2)
                    ->schema([
                        TextInput::make('meta_title')
                            ->label(__('admin.meta_title'))
                            ->placeholder(__('admin.seo_title'))
                            ->maxLength(255),
                        Textarea::make('meta_description')
                            ->label(__('admin.meta_description'))
                            ->placeholder(__('admin.seo_description'))
                            ->rows(3)
                            ->maxLength(500),
                        TextInput::make('meta_keywords')
                            ->label(__('admin.keywords_comma_separated'))
                            ->placeholder(__('admin.eg_hotel_travel_luxury'))
                            ->maxLength(500),
                    ]),
            ]);
    }
}
